### ISSUE TITLE
[Bug]: Missing fields in migration

### ISSUE THREAD

**Issue by remybroun** [joaopaulolndev/filament-general-settings#11]
### What happened?

I followed the instructions to install, everything went smoothly, however, there were missing fields when migrating. That was causing errors when saving the settings.

### How to reproduce the bug

-> install with documentation provided

Missing fields I needed to add manually to the migration:

            $table->string('mail_to')->nullable();
            $table->string('smtp_host')->nullable();
            $table->string('smtp_port')->nullable();
            $table->string('smtp_encryption')->nullable();
            $table->string('smtp_timeout')->nullable();
            $table->string('smtp_username')->nullable();
            $table->string('smtp_password')->nullable();
            $table->string('mailgun_domain')->nullable();
            $table->string('mailgun_secret')->nullable();
            $table->string('mailgun_endpoint')->nullable();
            $table->string('postmark_token')->nullable();
            $table->string('amazon_ses_key')->nullable();
            $table->string('amazon_ses_secret')->nullable();
            $table->string('amazon_ses_region')->nullable();
            $table->string('seo_description')->nullable();
            $table->string('seo_preview')->nullable();

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10

### Notes

After adding these fields, everything migrated and saved smoothly

**Comment by joaopaulolndev** [comment]
Hello,
How are you?

It is a little bit weird because these field values will be inside these json fields

$table->json('seo_metadata')->nullable();
$table->json('email_settings')->nullable();
            
Could you tell me the exact error or send me an email with a recorded video of this error?

Might be variable need to be unset before sending to the database

**Comment by hackie-me** [comment]
Getting same error after adding @remybroun listed fiealds there are still some fiealds missing 
here is the sql Error 
`Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_email_provider' in 'field list' (Connection: mysql, SQL: insert into `general_settings` (`site_name`, `theme_color`, `seo_description`, `seo_metadata`, `seo_preview`, `default_email_provider`, `smtp_host`, `smtp_port`, `smtp_encryption`, `smtp_timeout`, `smtp_username`, `smtp_password`, `site_description`, `support_email`, `support_phone`, `google_analytics_id`, `posthog_html_snippet`, `seo_title`, `seo_keywords`, `email_from_name`, `email_from_address`, `mail_to`, `social_network`, `email_settings`, `updated_at`, `created_at`) values (hello, ?, ?, [], ?, smtp, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, {"whatsapp":null,"facebook":null,"instagram":null,"x_twitter":null,"youtube":null,"linkedin":null,"tiktok":null,"pinterest":null}, {"default_email_provider":"smtp","smtp_host":null,"smtp_port":null,"smtp_encryption":null,"smtp_timeout":null,"smtp_username":null,"smtp_password":null,"mailgun_domain":null,"mailgun_secret":null,"mailgun_endpoint":null,"postmark_token":null,"amazon_ses_key":null,"amazon_ses_secret":null,"amazon_ses_region":null}, 2024-06-16 05:30:34, 2024-06-16 05:30:34))`

![image](https://github.com/joaopaulolndev/filament-general-settings/assets/71688178/78f24bd5-12ae-4c6c-a7d3-bd8829046c1b)

**Comment by joaopaulolndev** [comment]
Hey @remybroun  and @hackie-me 

Please, update to v1.0.11 and test.
Let me know here if working fine now because I can't replicate the issue on my side and even fix it.

**Comment by joaopaulolndev** [comment]
Nice @Sindoweb if something else happens let me know!
And thanks for this feedback
