### ISSUE TITLE
[Issue]: Side Navigation Getting Hidden when i add custom tabs in general setting config.

### ISSUE THREAD

**Issue by mohammedmushtaq3** [joaopaulolndev/filament-general-settings#13]
### What happened?

I cannot navigate to other pages after i add custom fields to the filament-general-setting config and when i do it the side

If i'm at any other page it is working

Image with No Field in more_configs.
![Screenshot 2024-06-22 at 3 29 21 PM](https://github.com/joaopaulolndev/filament-general-settings/assets/58843133/fe4f41f7-aea5-4cac-b56b-4eae1a0843a2)

Image with 1 Field in more_configs
![Screenshot 2024-06-22 at 3 30 33 PM](https://github.com/joaopaulolndev/filament-general-settings/assets/58843133/cd266030-ea56-4e13-b0f8-d4037929d2ad)

### How to reproduce the bug

Install the plugin and add atleast one custom field in more_configs fields.

### Package Version

1.0.11

### PHP Version

8.3.8

### Laravel Version

11.10.0

### Which operating systems does with happen with?

macOS

**Comment by edeoliv** [comment]
Hi @mohammedmushtaq3 I tried to reproduce the error but here it worked perfectly, 
Could you share your code so we can analyze it?

**Comment by mohammedmushtaq3** [comment]
I am really sorry for taking your time when i tried to recreate the issue in a brand new project they were no issue. When i faced this issue in 2 of my application existing project so i thought to report it. The issue should be with me where i am heavely customizing using tailwind config.
There is no issue with the plugin. i will be closing the issue.

**Comment by mohammedmushtaq3** [comment]
I will note it down and will let you know what the issue was if i am able to find why it is happening in my project.
