### ISSUE TITLE
[Bug]: After adding custom tabs Page loads in full screen

### ISSUE THREAD

**Issue by hackie-me** [joaopaulolndev/filament-general-settings#17]
### What happened?

After publishing config file, I have added custom tags, which leads to load page in Full screen, the filament navigation is hidden and visible only General settings page

### How to reproduce the bug

I have processed below things: 
step-1 : Run the command to publish config file `php artisan vendor:publish --tag="filament-general-settings-config"
`
step-2 : Edit config file 
`<?php

use Joaopaulolndev\FilamentGeneralSettings\Enums\TypeFieldEnum;

return [
    'show_application_tab' => true,
    'show_analytics_tab' => true,
    'show_seo_tab' => true,
    'show_email_tab' => true,
    'show_social_networks_tab' => true,
    'expiration_cache_config_time' => 60,
    'show_custom_tabs' => true,
    'custom_tabs' => [
        'more_configs' => [
            'label' => 'More Configs',
            'icon' => 'heroicon-o-plus-circle',
            'columns' => 1,
            'fields' => [
                'razor_pay_secret_key' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Secret Key',
                    'placeholder' => 'Enter your secret key',
                    'required' => false,
                    'rules' => 'required|string|max:255',
                ],
                'razor_pay_public_key' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Public Key',
                    'placeholder' => 'Enter your public key',
                    'required' => false,
                    'rules' => 'required|string|max:255',
                ],
                'admin_url' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Admin URL',
                    'placeholder' => 'Enter your admin url',
                    'required' => false,
                    'rules' => 'required|string|max:255',
                ],
            ]
        ]
    ]
];
`

### Package Version

1.0.15

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

Windows

**Comment by joaopaulolndev** [comment]
Fixed, please update and test again.
