### ISSUE TITLE
[Bug]: Livewire Entangle Error

### ISSUE THREAD

**Issue by abdosaeedelhassan** [joaopaulolndev/filament-general-settings#6]
### What happened?

Livewire Entangle Error: Livewire property ['data.seo_description'] cannot be found on component: ['joaopaulolndev.filament-general-settings.pages.general-settings-page']

Livewire Entangle Error: Livewire property ['data.seo_preview'] cannot be found on component: ['joaopaulolndev.filament-general-settings.pages.general-settings-page']

Livewire Entangle Error: Livewire property ['data.theme_color'] cannot be found on component: ['joaopaulolndev.filament-general-settings.pages.general-settings-page']

### How to reproduce the bug

I think this field need default value when working at first time

### Package Version

1.0.8

### PHP Version

8.2.0

### Laravel Version

11.8.0

### Which operating systems does with happen with?

Linux

**Comment by joaopaulolndev** [comment]
Hello @abdosaeedelhassan 

Fixed in v1.0.9, please update the package and try again.

Many thanks!
